"""Reference values for `test_examples.py`.

Regenerate the whole table with

    uv run python tests/test_examples.py

but do so only if the change is *intended*: these values encode the (verified)
agreement with the original Matlab codes.

Provenance:

- `quarter_five_spot` was generated by `matlab_codes/listing9.m`: `S(1:600:end)`.
- The others were generated by TPFA-ResSim itself
  (`rate_scheduling` at an early commit; the rest when they were written).
- `buildup` was re-generated when it was re-posed in metric units
  (ref `TPFA_ResSim.ResSim.cdarcy`), so its values are in bar, `perm_est` in mD.
- `buckley_leverett` is the exception to all of the above: it does not rest on
  agreement with anything of ours -- the example itself asserts its agreement
  with the *analytic* solution. Its `welge` and `bt` values therefore double as
  a record that the analytics are being *derived*, not merely reproduced.
"""

references = {
    "buckley_leverett": dict(
        explicit = [0.990913, 0.890405, 0.822983, 0.765383, 0.706094, 0, 0, 0],
        implicit = [0.990162, 0.883361, 0.811672, 0.747063, 0.65349, 0, 0, 0],
        case_B = [0.777523, 0.629058, 0.568955, 0.527966, 0.497229, 0.4696, 0.433861, 0.2],
        welge = [0.707107, 1.20711, 0.444949, 2.87457],
        water_cut = [0.0856744, 0.869728, 0.892704, 0.908574, 0.919621, 0.929471, 0.937468, 0.944081],
        bt = [0.82, 0.828427],
        L1 = [0.0268856, 0.0150174, 0.00684973, 0.00493806, 0.00233683],
    ),
    "buildup": dict(
        p_cell = [250, 232.86, 230.873, 246.473, 246.956, 246.996, 246.999, 247],
        p_far = [250, 249.567, 248.077, 246.99, 246.97, 246.984, 246.991, 246.995],
        p_mean = [250, 249, 247.5, 247, 247, 247, 247, 247],
        p_final = [247.009, 247.008, 247.006, 247.002, 246.998, 246.994, 246.992, 246.991],
        perm_est = [96.2918],
    ),
    "depletion": dict(
        p_mean = [1, 0.965, 0.93, 0.895, 0.8575, 0.8225, 0.7875, 0.75],
        p_cell = [1, 0.815102, 0.77981, 0.744795, 0.707292, 0.672291, 0.637291, 0.599791],
        p_last = [0.766962, 0.755348, 0.759947, 0.736761, 0.744617, 0.751904, 0.752602, 0.760441],
    ),
    "heterogeneous": dict(
        pres_coarse = [-1.22125e-15, -0.698729, -1.02616, -1.25968, -1.4693, -1.70281, -2.03025, -2.72898],
        pres_fine = [-5.7454e-15, -1.2919, -0.961099, -1.53098, -1.29976, -1.83924, -1.48946, -4.16618],
    ),
    "pressure_diffusion": dict(
        dp_early = [0.314632, 0.00132661, 0.01226, -0.000672055, 0.000821872, -0.0108189, -0.00101512, -0.314632],
        dp_late = [0.559039, 0.0422538, 0.132284, -0.0225223, 0.0273494, -0.12519, -0.0354479, -0.559039],
        elliptic = [0.561286, 0.0429973, 0.13397, -0.022919, 0.0278314, -0.126825, -0.0360858, -0.561286],
        p_inj = [1, 1.43087, 1.50322, 1.52776, 1.54501, 1.5518, 1.55667, 1.55904],
    ),
    "quarter_five_spot": dict(
        # These 3 rows agree with the Matlab output (whose values are quoted here
        # to their 5 decimals: .99965, .91968, .77584, .90268, .81068, .67467, .66065
        # for the explicit scheme, and .99963, .91573, .75736, .89799, .79862,
        # .62061, .62483 for the implicit one).
        explicit = [0.999653, 0.919677, 0.775843, 0.902681, 0.810679, 0.674671, 0.660654],
        implicit = [0.999629, 0.915725, 0.757356, 0.897986, 0.798623, 0.620613, 0.62483],
        doubled = [0.999826, 0.955246, 0.861405, 0.944767, 0.888273, 0.825464, 0.807728],
    ),
    "rate_scheduling": dict(
        sat_final = [0.99949, 0.881942, 0.826531, 0.878561, 0.776629, 0.710515, 0.11659],
    ),
    "voidage_replacement": dict(
        sat_full = [0.999515, 0.934951, 0.976032, 0.899993, 0.929288, 0.874472, 0.856937, 0.825724],
        sat_half = [0.998472, 0.847911, 0.933851, 0.797146, 0.840301, 0.768707, 0.732017, 0.706502],
        prd_full = [0, 0, 0, 0.591944, 0.713273, 0.768264, 0.80234, 0.825724],
        prd_half = [0, 0, 0, 0, 0.530559, 0.629839, 0.679435, 0.706502],
        p_half = [15, 13.6, 12.15, 10.75, 9.3, 7.9, 6.45, 5],
    ),
    "well_control": dict(
        rate_of_bhp_ctrl = [0.622077, 0.341664, 0.21485, 0.135109, 0.0831082, 0.0522631, 0.032866, 0.0202164],
        bhp_of_rate_ctrl = [0.79906, 0.667281, 0.562276, 0.457276, 0.347276, 0.242276, 0.137276, 0.0272763],
        p_last_bhp_ctrl = [0.519567, 0.518555, 0.518959, 0.516987, 0.517654, 0.518229, 0.518302, 0.518945],
        rate_of_limited = [0.25, 0.25, 0.25, 0.205883, 0.126636, 0.079636, 0.0500796, 0.0308049],
        bhp_of_limited = [0.79906, 0.667281, 0.562276, 0.5, 0.5, 0.5, 0.5, 0.5],
    ),
    "well_path": dict(
        alloc_static = [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625],
        alloc_bhp = [0.0128816, 0.0131298, 0.0138058, 0.0148435, 0.0161053, 0.0173625, 0.0183188, 0.0187026],
        sat_point = [0.999653, 0.919677, 0.775843, 0.902681, 0.810679, 0.674671, 0.660654],
        sat_path = [0.980677, 0.903463, 0.85529, 0.785376, 0.749434, 0.752974, 0],
    ),
}
