"""Reference values for `test_examples.py`.

Regenerate the whole table with

    uv run python tests/test_examples.py

but do so only if the change is *intended*: these values encode the (verified)
agreement with the original Matlab codes.

Provenance:

- `quarter_five_spot` was generated by `matlab_codes/listing9.m`: `S(1:600:end)`.
- The others were generated by TPFA-ResSim itself
  (`rate_scheduling` at an early commit; the rest when they were written).
"""

references = {
    "buildup": dict(
        p_well = [1, 0.85361, 0.951564, 0.980384, 0.985436, 0.98679, 0.987242, 0.987405],
        p_far = [1, 0.998068, 0.991799, 0.987621, 0.987034, 0.987093, 0.987187, 0.987267],
        p_mean = [1, 0.993, 0.9875, 0.9875, 0.9875, 0.9875, 0.9875, 0.9875],
        p_final = [0.988011, 0.98764, 0.987843, 0.987379, 0.98756, 0.987182, 0.98737, 0.987126],
    ),
    "depletion": dict(
        p_mean = [1, 0.965, 0.93, 0.895, 0.8575, 0.8225, 0.7875, 0.75],
        p_well = [1, 0.815102, 0.77981, 0.744795, 0.707292, 0.672291, 0.637291, 0.599791],
        p_last = [0.766962, 0.755348, 0.759947, 0.736761, 0.744617, 0.751904, 0.752602, 0.760441],
    ),
    "heterogeneous": dict(
        pres_coarse = [-1.22125e-15, -0.698729, -1.02616, -1.25968, -1.4693, -1.70281, -2.03025, -2.72898],
        pres_fine = [-5.7454e-15, -1.2919, -0.961099, -1.53098, -1.29976, -1.83924, -1.48946, -4.16618],
    ),
    "pressure_diffusion": dict(
        dp_early = [0.314632, 0.00132661, 0.01226, -0.000672055, 0.000821872, -0.0108189, -0.00101512, -0.314632],
        dp_late = [0.556059, 0.0423476, 0.132225, -0.0224157, 0.0274534, -0.12523, -0.0353491, -0.562059],
        elliptic = [0.561286, 0.0429973, 0.13397, -0.022919, 0.0278314, -0.126825, -0.0360858, -0.561286],
        p_inj = [1, 1.42946, 1.50097, 1.52521, 1.54223, 1.54893, 1.55372, 1.55606],
    ),
    "quarter_five_spot": dict(
        # These 3 rows agree with the Matlab output (whose values are quoted here
        # to their 5 decimals: .99965, .91968, .77584, .90268, .81068, .67467, .66065
        # for the explicit scheme, and .99963, .91573, .75736, .89799, .79862,
        # .62061, .62483 for the implicit one).
        explicit = [0.999653, 0.919677, 0.775843, 0.902681, 0.810679, 0.674671, 0.660654],
        implicit = [0.999629, 0.915725, 0.757356, 0.897986, 0.798623, 0.620613, 0.62483],
        doubled = [0.999826, 0.955246, 0.861405, 0.944767, 0.888273, 0.825464, 0.807728],
    ),
    "voidage_replacement": dict(
        sat_full = [0.998711, 0.933913, 0.97424, 0.899656, 0.928366, 0.874886, 0.857094, 0.826569],
        sat_half = [0.969699, 0.645641, 0.766313, 0.582563, 0.634495, 0.54789, 0.516044, 0.497839],
        prd_full = [0, 0, 0, 0.593332, 0.714602, 0.769496, 0.80338, 0.826569],
        prd_half = [0, 0, 0, 0, 0.390265, 0.470989, 0.491956, 0.497839],
        p_half = [15, 13.6, 12.15, 10.75, 9.3, 7.9, 6.45, 5],
    ),
    "rate_scheduling": dict(
        sat_final = [0.99949, 0.881942, 0.826531, 0.878561, 0.776629, 0.710515, 0.11659],
    ),
}
